config/routes.rb
Keijiban2::Application.routes.draw do
  resources :boards do
    resources :comments, except: [:index, :new, :show]
  end

  root to: 'boards#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { in: 4..32 }, uniqueness: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope order("created_at DESC")
  belongs_to :board
  validates :content, length: { in: 1..400 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new params_board
    if @board.save
      redirect_to board_path(@board)
    else
      render :new
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update_attributes params_board
      redirect_to board_path(@board)
    else
      render :edit
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def params_board
    params.require(:board).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @board = Board.find(params[:board_id])
    @comment = @board.comments.build params_comment
    if @comment.save
      redirect_to board_path(@board)
    else
      render :edit
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
    @comment.update_attributes params_comment
    redirect_to board_path(@board)
  end

  def destroy
    @board = Board.find(params[:board_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to board_path(@board)
  end

  private

  def params_comment
    params.require(:comment).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/boards/edit.html.erb
<% if @board.errors.any? %>
  <h2>エラーが発生したよ。</h2>
  <% @board.errors.full_messages.each do |f| %>
    <%= f %>
  <% end %>
<% end %>


<%= form_for @board do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/boards/index.html.erb
<% @boards.each do |b| %>
  <%= b.name %>
  <%= link_to 'show', board_path(b) %>
  <br>
<% end %>

<hr>

<%= link_to '新しいスレ作っぞ', new_board_path() %>

app/views/boards/new.html.erb
<% if @board.errors.any? %>
  <h2>エラーが発生しました.</h2>
  <% @board.errors.full_messages.each do |e| %>
    <%= e %>
  <% end %>
<% end %>


<%= form_for @board do |f| %>
  <%= f.text_field :name, placeholder: 'ここにタイトル書け' %>
  <%= f.submit %>
<% end %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>

<%= link_to '編集します', edit_board_path(@board) %>
<br>
<%= link_to '消去します', board_path(@board), method: :delete, confirm: 'このboardを消去します' %>

<hr>

<h1>Comments</h1>
<% @board.comments.each do |c| %>
  <p>
  <%= c.content %>
  <br>
  <%= c.created_at.strftime("%Y/%M/%D") %>
  <br>
  <%= link_to '編集するぜ', edit_board_comment_path(@board, c) %>
  <br>
  <%= link_to '削除するぜ', board_comment_path(@board, c), method: :delete, confirm: '削除するよ？' %>
  </p>
<% end %>

<hr>

<h1>new comment</h1>
<%= form_for [@board, @board.comments.build] do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<hr>

<%= link_to '一覧ページに戻るよ！', boards_path() %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
  <%= @comment.errors.full_messages.each do |e| %>
    <%= e %>
  <% end %>
<% end %>

<%= form_for [@board, @comment] do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Keijiban2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>